# Generated by Django 4.2.4 on 2023-09-02 20:34

import auctions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=auctions.models.user_directory_path),
        ),
    ]
