# Generated by Django 4.2.4 on 2023-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='lastBidTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
