# Generated by Django 4.2.4 on 2023-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_lastbidtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
