# Generated by Django 4.2.4 on 2023-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home and Garden', 'Home and Garden'), ('Toys and Games', 'Toys and Games'), ('Books', 'Books'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Automotive', 'Automotive'), ('Jewelry and Watches', 'Jewelry and Watches'), ('Collectibles', 'Collectibles'), ('Health and Beauty', 'Health and Beauty'), ('Music and Instruments', 'Music and Instruments'), ('Art and Crafts', 'Art and Crafts'), ('Food and Beverages', 'Food and Beverages'), ('Pets', 'Pets'), ('Travel and Experiences', 'Travel and Experiences'), ('Other', 'Other')], default='uncategorized', max_length=50),
        ),
    ]
